{
    "name": """Multi Website Portal""",
    "summary": """Multi Website support in Portal""",
    "category": "Portal",
    # "live_test_url": "http://apps.it-projects.info/shop/product/website-multi-company?version=10.0",
    "images": ["images/website_multi_company_portal_main.png"],
    "version": "11.0.1.0.0",
    "application": False,
    "author": "IT-Projects LLC, Ivan Yelizariev",
    "support": "apps@itpp.dev",
    "website": "https://twitter.com/OdooFree",
    "license": "Other OSI approved licence",  # MIT
    "depends": ["website_multi_company", "portal"],
    "external_dependencies": {"python": [], "bin": []},
    "data": [],
    "qweb": [],
    "demo": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}
