{
    "name": """SEO URLs in eCommerce""",
    "summary": """Customisable URLs for product pages, that don't depend on product name and product ID""",
    "category": "eCommerce",
    "images": [],
    "vesion": "13.0.1.0.0",
    "author": "IT-Projects LLC, Ivan Yelizariev",
    "support": "apps@itpp.dev",
    "website": "https://itpp.dev",
    "license": "Other OSI approved licence",  # MIT
    "price": 9.00,
    "currency": "EUR",
    "depends": ["website_seo_url", "product"],
    "external_dependencies": {"python": [], "bin": []},
    "data": ["views.xml"],
    "qweb": [],
    "demo": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "installable": False,
    "auto_install": False,
}
