{
    "name": """Multi Ecommerce""",
    "summary": """Multi Website support in eCommerce""",
    "category": "eCommerce",
    # "live_test_url": "http://apps.it-projects.info/shop/product/website-multi-company?version=11.0",
    "images": ["images/website_multi_company_sale_main.png"],
    "version": "11.0.1.5.1",
    "application": False,
    "author": "IT-Projects LLC, Ivan Yelizariev",
    "support": "apps@itpp.dev",
    "website": "https://twitter.com/OdooFree",
    "license": "Other OSI approved licence",  # MIT
    "depends": ["website_multi_company", "website_sale", "ir_rule_website"],
    "external_dependencies": {"python": [], "bin": []},
    "data": [
        "views/product_public_category_views.xml",
        "views/website_views.xml",
        "views/product_template_views.xml",
        "views/payment_views.xml",
        "views/sale_views.xml",
        "security/website_multi_company_sale_security.xml",
        "data/default_theme_data.xml",
    ],
    "qweb": [],
    "demo": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}
