from . import product_public_category
from . import sale_order
from . import product_template
from . import payment_acquirer
from . import website
from . import product_pricelist
from . import res_country
from . import res_partner
from . import res_config_settings
from . import res_company
from . import res_users
