{
    "name": "Website Sale Search Clear",
    "summary": """Clear the search""",
    "category": "eCommerce",
    "version": "13.0.1.0.1",
    "application": False,
    "author": "IT-Projects LLC, Ivan Yelizariev, Savoir-faire Linux, Nicolas JEUDY, Quartile Limited Tim Lai",
    "license": "Other OSI approved licence",  # MIT
    "support": "apps@itpp.dev",
    "website": "https://twitter.com/yelizariev",
    "price": 30.0,
    "currency": "EUR",
    "images": ["images/search.png"],
    "depends": ["website_sale"],
    "data": [],
    "post_load": "post_load",
    "pre_init_hook": None,
    "post_init_hook": None,
    "auto_install": False,
    "installable": True,
}
