{
    'name': "Website Sale Search Clear",
    'summary': """Clear the search""",
    'category': 'eCommerce',
    'version': '11.0.1.0.1',
    'application': False,
    'author': 'IT-Projects LLC, Ivan Yelizariev, Savoir-faire Linux, Nicolas JEUDY, Quartile Limited Tim Lai',
    'license': 'GPL-3',
    "support": "apps@it-projects.info",
    'website': 'https://twitter.com/yelizariev',
    'price': 30.0,
    'currency': 'EUR',
    'images': ['images/search.png'],
    'depends': ['website_sale'],
    'data': [],
    'post_load': 'post_load',
    'pre_init_hook': None,
    'post_init_hook': None,

    'auto_install': False,
    'installable': True,
}
